name: Run Unit Tests

description: Run Unit Tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - uses: 'ramsey/composer-install@v2'
      name: Install Composer & Dependencies
      
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        php_extensions: xdebug
        args: tests --coverage-clover coverage.xml
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage.xml
