name: Run Unit Tests

description: Run Unit Tests

inputs:
  ATAR_PROJECT:
    required: true
    description: ""
  ATAR_CREDENTIALS:
    required: true
    description: ""
  ARTIFACT_LOCATION:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      run: |
        echo ${{ inputs.ATAR_CREDENTIALS }}|gcloud auth activate-service-account --key-file=-
        echo @atarb2b:registry=https://${{ inputs.ARTIFACT_LOCATION }}-npm.pkg.dev/${{ inputs.ATAR_PROJECT }}/atar-fe-cli/ > .npmrc
        echo '//${{ inputs.ARTIFACT_LOCATION }}-npm.pkg.dev/${{ inputs.ATAR_PROJECT }}/atar-fe-cli/:always-auth=true' >> .npmrc
        npx google-artifactregistry-auth --repo-config=.npmrc --credential-config=.npmrc
        npm install
      shell: bash

    - run: npm run ci
      shell: bash

    - run: npm run build
      shell: bash

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/lcov.info