name: Run Unit Tests

description: Run Unit Tests

inputs:
  SSH_PRIV_KEY_LIBRARY:
    required: true
    description: SSH Private Key Library

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    # - name: Update Library
    #   uses: AtarB2B/github-library-workflow@main
    #   with:
    #     SSH_PRIV_KEY_LIBRARY: ${{ inputs.SSH_PRIV_KEY_LIBRARY }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip ; pip install flake8 pytest faker coverage pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f development/requirements.txt ]; then pip install -r development/requirements.txt; fi
        if [ -f library/requirements.txt ]; then pip install -r library/requirements.txt; fi
      shell: bash

    - name: Check format
      run: |
        pycodestyle ./app; isort --check-only ./app
      shell: bash

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash
    
    - name: Test with pytest
      run: ENV='test' pytest --ignore=app/main
      shell: bash
    
    - name: Test Coverage with pytest
      run: ENV='test' pytest --cov-config=.coveragerc --cov-report=html --cov=. app/
      shell: bash
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: htmlcov
        path: htmlcov/index.html
