name: Run Unit Tests

description: Run Unit Tests

inputs:
  TESTS_PATCH:
    required: true
    description: TESTS_PATCH

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
      
    # - name: Update Library
    #   uses: AtarB2B/github-library-workflow@main

    - name: Update Library
      run: |
        echo $ATARB2B_API_CREDENTIALS_PROD
        python -m pip install --upgrade pip ; pip3 install pylint pytest pytest-mock faker coverage pytest-cov keyring keyrings.google-artifactregistry-auth
        echo $ATARB2B_API_CREDENTIALS_PROD|gcloud auth activate-service-account --key-file=-
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      shell: bash

    - name: Pylint - Check Errors
      run: |
        pylint app/ --disable=all --enable=e,f
      shell: bash

    - name: Pytest - Test Coverage
      run: ENV='test' pytest --junitxml=result.xml --ignore=library/ --cov-config=.coveragerc --cov-report=xml --doctest-modules --cov=. ${{ inputs.TESTS_PATCH }}
      shell: bash
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage.xml 
  
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: result.xml
