name: Run Unit Tests

description: Run Unit Tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    
    - name: Working directory
      run: cd erp
      shell: bash

    - name: Test Coverage with jest
      uses: stefanoeb/jest-action@1.0.3
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: erp/coverage/lcov.info