name: Run Unit Tests

description: Run Unit Tests

inputs:
  SSH_PRIV_KEY_LIBRARY:
    required: true
    description: SSH_PRIV_KEY_LIBRARY

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    # - name: Check format
    #   run: |
    #     pycodestyle ./app; isort --check-only ./app
    #   shell: bash

    - name: Update Library
      uses: AtarB2B/github-library-workflow@main
      with:
        SSH_PRIV_KEY_LIBRARY: ${{ inputs.SSH_PRIV_KEY_LIBRARY }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip ; pip3 install pylint pytest faker coverage pytest-cov
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        if [ -f development/requirements.txt ]; then pip3 install -r development/requirements.txt; fi
        if [ -f library/requirements.txt ]; then pip3 install -r library/requirements.txt; fi
      shell: bash

    - name: Pycodestyle - Check Format
      run: |
        pycodestyle ./app; isort --check-only ./app
      shell: bash

    - name: Pylint - Check Errors
      run: |
        pylint app/ --disable=all --enable=e,f
      shell: bash

    - name: Pytest - Test Coverage
      run: ENV='test' pytest --junitxml=result.xml --ignore=library/ --cov-config=.coveragerc --cov-report=xml --doctest-modules --cov=. app/
      shell: bash
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage.xml 
  
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: result.xml
