name: Run Unit Tests

description: Run Unit Tests

inputs:
  SSH_PRIV_KEY_TOOLING:
    required: true
    description: SSH_PRIV_KEY_TOOLING
  GITHUB_TOKEN:
    required: true
    description: Github Token

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Config ssh-key
      run: |
        chown -R $(id -u):$(id -g) $PWD
        
        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"

        echo "${{ inputs.SSH_PRIV_KEY_TOOLING }}" > ssh-rsa.key
        chmod 400 ssh-rsa.key
        mkdir ~/.ssh && touch ~/.ssh/known_hosts
        eval $(ssh-agent) && ssh-add ssh-rsa.key
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      shell: bash

    - run: |
        echo @atarb2b:https://npm.pkg.github.com/ > .npmrc
        echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      shell: bash

    - name: Test Coverage
      run: |
        npm install
        npm run ci .
      env:
          NPM_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/lcov.info