name: Run Unit Tests

description: Run Unit Tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
