name: Run Unit Tests

description: Run Unit Tests

inputs:
  TESTS_PATCH:
    required: true
    description: TESTS_PATCH

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Pylint - Check Errors
      run: |
        pylint app/ --disable=all --enable=e,f
      shell: bash

    - name: Pytest - Test Coverage
      run: ENV='test' pytest --junitxml=result.xml --ignore=library/ --cov-config=.coveragerc --cov-report=xml --doctest-modules --cov=. ${{ inputs.TESTS_PATCH }}
      shell: bash
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage.xml 
  
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: result.xml
